// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRj6QcC13EgGgn8X5FUCdNHIJbLbF-WIU',
    appId: '1:1097242350126:web:3fa67376fca36c1805c5bf',
    messagingSenderId: '1097242350126',
    projectId: 'apprastreogt',
    authDomain: 'apprastreogt.firebaseapp.com',
    storageBucket: 'apprastreogt.appspot.com',
    measurementId: 'G-JE1ZHZQ4NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0E_HuShmvPAeynPlczVt1zscSgTzrhek',
    appId: '1:1097242350126:android:15ed4c638238488705c5bf',
    messagingSenderId: '1097242350126',
    projectId: 'apprastreogt',
    storageBucket: 'apprastreogt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1OxmCBcC5dC0M63hGkbC57fSUhJlLVi4',
    appId: '1:1097242350126:ios:85b1bf3af4f21f6a05c5bf',
    messagingSenderId: '1097242350126',
    projectId: 'apprastreogt',
    storageBucket: 'apprastreogt.appspot.com',
    iosClientId: '1097242350126-3lej82dv40chi3h3a3ro87jp2b6fo2un.apps.googleusercontent.com',
    iosBundleId: 'com.example.appseguimiento',
  );
}
